sudo: required
#language: ruby
#cache: bundler
services:
- docker
  #before_install:
  # - gem update --system
  # - gem install bundler:2.0.1
install: true
addons:
  apt:
    packages:
      - docker-ce
before_script:
        #- sudo apt update -y
        #- sudo apt install --only-upgrade docker-ce -y
- sudo service postgresql stop
- sudo cp .env.test .env
- env
- export

env:
  global:
  - secure: aTy4+EDSJ4mnzoIMTLosYLadb92dpuI1VYaKY3z917Ks2ugtKyhUl9DnImQWdAZwnt54Q+1s8Y5Dv62qNvG5Z1ESTFrqiFuJvxDJGLKjIK3D7LO/6DZK8uHLSkZEk90k/xgl6YTaMGDlFlnTS7pikFxSoUFsYXdMC3LH3mkdlQqSlbBrs8RD0x4NEBL3NCAl10WNpKAcTLYTPcy2rBcCYYB3v3zfbO+7VNK3qxIjNSmgpqW5XdC/I+E7gRroGfwLG7M7nmvMC6KAMT5fMfpoaiLTTSspk4D6SCioYwvhotNsTFAkAidcQvNr2phKsvKmxXEWtWSPk8iE7HpUTvyGj47ESgHA6aJmYUs2m8vySJjSWhFejy2XKwYqK8nCL6DtCkdu24WDj4knumFDRoUe5VvchosR6ntqUs3xT6Y4+1XW4WIN8rUK7W1/AjHruhqsigwvEhrave+/e9MSJ1w2qgmSJGLJ+h3Y+4/LSr0sosqZWgOH91WIPEHgUl/hFZMqRs31lyR38fdbnjTcJNFLpQkYtitxLfRaq9Zf5UHtxCT36dL5P1QCAxyGBxteZKTO+ACLLHrBxlaRlPoVOYrT7wvADIlsm3jDXhdkf9rf2ZQs/cOD91uKFyInWE/CpL2/Atp1RFUrgWbvoR3/sRC/wz78A4+VepyVMjOSzE85S1Q=
  - secure: TYHzYfFxRpqILrcGIBgDkUVRHHDKJxAnhtMJ44OFB9YD/fWgTxWl04nd4YA/KvxId0d5nrq7z0O4zF4e6ZEHagCnv9ZG4Xc3kVLzkhCp4ZIqBKMkBd5copZGNZAjRVH6e6fsXQhUK/hVTULhtyvNVr950fWrZzk00lfRLn+F7J8AbWAxqKPEhaiJIH0NdfsoQti1GRC98g6vpeLWDP/OyNUPc73xH0ALS/1fiPILTLESM6w06OuLHn5j1GqJPowMYhVR7bDwOXKvpdbljp3V9vWOv0o6gEPvfJJC0YZdWjw7ncCo8Guy11NDBPibcF6x9uzE6dV4O3zA7/RRJV5PJGt7dCeYqKZt4aY2fJsBupVXi2a1N/qFwN8uIWh1g6yNKGa9kxznh727PAet+G8ucncwzBu+FRSlFdJUpif4eLpVPaebnVNXc6PpwFbOUftP12sM2EbvPuu/sA4q6FNYg/R0ydsvFt6/IEgV25pmJYF+2ZFz91W1L0STxMcl78kXsyoyDhRIdEBoM/3RlmggqUAkQ06BQ41/SJJnnY/38dsPLlK/pTcN/fzYuL25IyOFG7P8gpBTHanzjS7Bejc2T3S0hsNTkliGwSk3V+aJzrAGcp+A9XVbMTXg8OchUjKRe1Io2/E9NcyrIfctaLtKeZ2EOxx+ra9r4sjkjbcGpbk=
  - secure: "hYYli+x4TUHfhphGwrkI539FOEi1xJVdUZ6gs5Ru5qVyxAxUldhbxWWqfKyNgqLgJs1CVjrnXqgNiE+FvLz5+TbSVJu62YBuzTBKbEnbZi17Ibtl2XDcbYFyuFX2dOg2hgRgJBVArFHm7/NcEbESfK+RFovfN8U8Og92iTLo7amgOOof8W54BWJuW46Cx4H8kZPPTbKQIldvnLvlA0nRjFMhnES4aY6qduFwER5Tl3plERDxyYSxi2IXAs5ZyOBVELUEjJJQ1DjP57MfR9kmbYqt9TdCoSXxBKXKGGP2jBvzHmtDDIe4Sdb24qUvAP62s+B3AEQhD7NXVwjNVWxqexfQqj+XyHIrE5OAApA0+snEn65ZUJvIHtD/irrpA8w5t/B+/2yH+4PV4GylCeMqkswmJPWxGTvnhSDxjc/3q28zFUrIV7Hkg3dS7ResJvL97hz3bKIlDQ3duQe+87+Ez/a8B7kTwktHed7dauYUhw96YBwxdtTX+Hc+TVyFej0esl8C6STcG/061m+K1cbc4V3UXHaSC5PDxKVr04hh9T86JUX07+vaZGpO8LIw3I1IZef6L1bWdn39SxNacIl5O7jpezb80PVFRx2C5y7bN8I3hYpWpDJKQlowpkPuqlhWXgd6QRhD1s+rdF9y2vmk745tl/aCyLOZaEvzZTR0LsI="
  - secure: "edWJf3HhM7xYfyiFiZXOFpEpnhbRsZ1njetRQcc5d7lcZ+GrRi7a6kjMqiNVnwQ8nFF/+fLMTSLE6v5dNoX+WgvMkfmK5GDeUQ1EtDXBYMxUaB5qyNfT7WOm/JFzMGAp2R+22xTTx04K3leaREVracHL5OL8JSXD7qtwYIuRPenBokZtMzKaPHXe9L90q5Y/xoWX5T2+7LHtIqviz0bQ5eRJCqEXnHzC3wEQ6kVxNHXvmUptBjC9XH6dT/IG5pKrkLUJEyxyKzoZrRIAIzz6frzzsAr51g/ZZD2W7lWw2YD8Yqq6Mkh5ZcX1Rs5+2MrlG085Lhe+0DD9KahuQvm8pVj4IJ712CNHecgkr53uKRfZ2KmMBSHTv3/1xlcT2gTxmz8hwvrMY8cjgdDKpIFNDWzMPYjgdLG+4hFFiqNrT01yP2/n39a3yJcH3VH+aPB7ywSr3pFlnQ1/LAVMjyulwegL81n94vVr7awL+YfPna4yrevsfnKleAAPJ8/mbEucjPPH1AAVm28b5lWzpG4SsWB64SGNt1WIl239mPn45+DGsRAdFU0oXmuI7se0ILmcihWS4V+KsxWEc3i0goSXxkNqMM6ro4sM5uF5gfslnXSBmXkJEP1JOcekOaVBSjNvXiDRzjpZ11w7xIDDTrW0U2yY0t5LGj/HMZBN2lSyDKE="
script:
        #- docker pull aptrust/pharos:latest
- make test-ci
deploy:
- provider: script
  script: make -w publish-ci
  on:
    branch: feature/two_factor
  skip_cleanup: true
notifications:
    slack:
      secure: H5vU3wRKiO5VCBNThkEfT5uhpZVa710PnaRzfSM1wfX95X5JvV7NmH8AwbGtpe90O5gpub2kEji7WIFtshRwVCFwcjvA11pWUH7Q2K5fs6mcSoIFTXXptNW2jnbC8a11yiMPu41BFVOphQQk/mDMIhP95RN0+Zr7x92zzn/LwRETW1OseJN05KpOE0CLTaOv8apJecpVzcw55sNuCD2Ztrlu9tut45rKBKCEGUta4YImWey5RgxKYgP+7I7K7ImueRCZuKWMbYtmVaYSF7/hf23xwD5jESVpq/xlf89B3JOpu3NQL6ZNQHfMvGZwjHkgTAnO/D/zWD+kUVTs1ulgbVbeJqxtT/mAqiWVCagX7QHOSirwJ7Se4jjAU4LpNAvtXGFuRKZNiNDtDm1beQGbwmrMoTN22FykQwkDm1bWwUQCuFEsSNi1yHS7pN+RNAyqIYOqdn9KjZT/TMxsWRfp/+z3rReh7GBZTsDzGaNG46gUUJDcYLcgO7jpAiu7wcM2md9Q0qmmZ8LP3cZzHyde3k4MYNL+ETZXrAzJOxN6liUW+TgdfyD5mK632OVImCRyxLv6NKvTCL/YhpRRymI0gYLhENy3BgM/yZPV62qfVxyAxUrtFF9hwcXd3Nzj56hFmBCuNXRnF2jnMETv9tzQZaGARcEbGMaHw/hLSXYBtpE=
