language: ruby

sudo: required

env:
  global:
  - CACHE_DIR=$HOME/.cache/docker

services:
  - docker

before_install:
  # Load cached docker images - https://github.com/travis-ci/travis-ci/issues/5358
  - if [[ -d $HOME/docker ]]; then ls $HOME/docker/*.tar.gz | xargs -I {file} sh -c "zcat {file} | docker load"; fi

cache:
  directories:
  - $CACHE_DIR

before_script:
    - sudo apt update -y
    - sudo apt install --only-upgrade docker-ce -y
    - sudo service postgresql stop
    - docker build -t pharos-ci:latest .
    - docker network create -d bridge pharos-test-net
    - docker run -d --network pharos-test-net --hostname pharos-test-db --name pharos-test-db -p 5432:5432 postgres:9.6.6-alpine
    - docker run -e RAILS_ENV=test -e PHAROS_DB_NAME=travis_ci_test -e PHAROS_DB_HOST=pharos-test-db -e PHAROS_DB_USER=postgres --network pharos-test-net --rm pharos-ci:latest /bin/bash -c "echo 'Init DB setup'; rake db:setup; rake db:migrate; rake pharos:setup"
     - export
     - docker run --rm -it --network pharos-test-net -e PHAROS_DB_NAME=travis_ci_test -e PHAROS_DB_HOST=pharos-test-db -e PHAROS_DB_USER=postgres pharos-ci:latest /bin/bash -c "bin/rails spec"

before_cache:
  # Save tagged docker images
  - >
    mkdir -p $HOME/docker && docker images -a --filter='dangling=false' --format '{{.Repository}}:{{.Tag}} {{.ID}}'
    | xargs -n 2 -t sh -c 'test -e $HOME/docker/$1.tar.gz || docker save $0 | gzip -2 > $HOME/docker/$1.tar.gz'
