language: ruby

sudo: required
cache:
  directories:
  - $CACHE_DIR

services:
  - docker

before_script:
    - sudo apt update -y
    - sudo apt install --only-upgrade docker-ce -y
    - make test-ci
env:
  global:
  - CACHE_DIR=$HOME/.cache/docker
  - PGPORT=5433



