language: ruby
rvm:
- 2.3.1
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - secure: XHjeFTlHHhdwdZfV6HzvCfovU2fRVPO3Uc7tBAHa8MRXPGaphxfvcJU4HSrDouWKemm/9As67NNocwKkLdyQ920spQ4+DJdnDnz0ifY7oLz98DBBoniXhtpaJQ1ahCl6l7754Rt5U6XNeHT71K4t5GSm4hrjHpq7mJpgRY6BzUs=
  - secure: ZBCss4Cr2QNh0lN3JcCCZkqU3AORpnRKVZP0WEjZIJdYnxeuirkZ3IdLgYL6dUVpt1/mv5bXD19UJh6TA5JNb3fN+Kx30jXVIUVBBYqU6iHqE6yV6a3rC4QJgCob1IlZStJ9QxBNWo5nwEpEgrfJbz8s7extrYTQNq3GB2AR9a0=
notifications:
  slack:
    secure: hv4ZRlEa/2PZCbcTeFpmNoSpUkwFB1moAPFNoPMYxpZanAYYi5Y/5/IKJjMDslDIgTAPoc3OkCWqHOI/0Jz6t2cT6KozWfrWd+JmLuGEuTqx/KJvk0rSvtkkUlWrb5knIIJDB81Cu02MVOo+9kRLqH8Ua0zZhDew7oaaX91Ifu4oumSMn72DOElEeqAtZNJajMfTN6Pp6ZkirbzmxiR/qR/Vi/2RfDAJwSKgXFujlE5OiZuRGXzHiJrkOVqBwJ9HohDhfr15nyp/6qw0mYExyhYH8cIc+sTDETBSLU7nrS5X2NC6/GwRyrY0i6WkBfxhliG9A7uMp+o8I8asH1eIOxc/fOUSNM5UGmopeIdFVKD7Rh6IxBpA4ekPTVhKY2WEIPgO4znYjJ4PPO+c1KhSANipBghkdt8HFuZoEOOiDbj5iwd15JlUuFxrTLqSPV04cCe/oPpSJOjE2te6jWHZpx6fTPomYAbfAzpxtpOd1H83uwOQYZMH1VqNhYysAwtM5f129inE4MIsVvouobDbAdG+Axu8E4+VptIoejznEhGahBbC+5P8VGP65UDKmfaBLAv1vDw2yuo1q3z8OFRcU5zZzKibPEte9Nohh7vlIScxv0uqf86BduldA1SB/MSzL0L6t5Rv2KPei5KFAfCZbqgU8YYgnU8QJut8Tp8zX9Y=
    on_success: change
    on_failure: always
branches:
  only:
  - master
  - develop
before_install:
- gem install bundler
before_script:
- bundle exec rake db:migrate RAILS_ENV=test
