sudo: required
services:
- docker
env:
  global:
  - secure: aTy4+EDSJ4mnzoIMTLosYLadb92dpuI1VYaKY3z917Ks2ugtKyhUl9DnImQWdAZwnt54Q+1s8Y5Dv62qNvG5Z1ESTFrqiFuJvxDJGLKjIK3D7LO/6DZK8uHLSkZEk90k/xgl6YTaMGDlFlnTS7pikFxSoUFsYXdMC3LH3mkdlQqSlbBrs8RD0x4NEBL3NCAl10WNpKAcTLYTPcy2rBcCYYB3v3zfbO+7VNK3qxIjNSmgpqW5XdC/I+E7gRroGfwLG7M7nmvMC6KAMT5fMfpoaiLTTSspk4D6SCioYwvhotNsTFAkAidcQvNr2phKsvKmxXEWtWSPk8iE7HpUTvyGj47ESgHA6aJmYUs2m8vySJjSWhFejy2XKwYqK8nCL6DtCkdu24WDj4knumFDRoUe5VvchosR6ntqUs3xT6Y4+1XW4WIN8rUK7W1/AjHruhqsigwvEhrave+/e9MSJ1w2qgmSJGLJ+h3Y+4/LSr0sosqZWgOH91WIPEHgUl/hFZMqRs31lyR38fdbnjTcJNFLpQkYtitxLfRaq9Zf5UHtxCT36dL5P1QCAxyGBxteZKTO+ACLLHrBxlaRlPoVOYrT7wvADIlsm3jDXhdkf9rf2ZQs/cOD91uKFyInWE/CpL2/Atp1RFUrgWbvoR3/sRC/wz78A4+VepyVMjOSzE85S1Q=
  - secure: TYHzYfFxRpqILrcGIBgDkUVRHHDKJxAnhtMJ44OFB9YD/fWgTxWl04nd4YA/KvxId0d5nrq7z0O4zF4e6ZEHagCnv9ZG4Xc3kVLzkhCp4ZIqBKMkBd5copZGNZAjRVH6e6fsXQhUK/hVTULhtyvNVr950fWrZzk00lfRLn+F7J8AbWAxqKPEhaiJIH0NdfsoQti1GRC98g6vpeLWDP/OyNUPc73xH0ALS/1fiPILTLESM6w06OuLHn5j1GqJPowMYhVR7bDwOXKvpdbljp3V9vWOv0o6gEPvfJJC0YZdWjw7ncCo8Guy11NDBPibcF6x9uzE6dV4O3zA7/RRJV5PJGt7dCeYqKZt4aY2fJsBupVXi2a1N/qFwN8uIWh1g6yNKGa9kxznh727PAet+G8ucncwzBu+FRSlFdJUpif4eLpVPaebnVNXc6PpwFbOUftP12sM2EbvPuu/sA4q6FNYg/R0ydsvFt6/IEgV25pmJYF+2ZFz91W1L0STxMcl78kXsyoyDhRIdEBoM/3RlmggqUAkQ06BQ41/SJJnnY/38dsPLlK/pTcN/fzYuL25IyOFG7P8gpBTHanzjS7Bejc2T3S0hsNTkliGwSk3V+aJzrAGcp+A9XVbMTXg8OchUjKRe1Io2/E9NcyrIfctaLtKeZ2EOxx+ra9r4sjkjbcGpbk=
before_script:
- sudo apt update -y
- sudo apt install --only-upgrade docker-ce -y
- sudo service postgresql stop
- sudo cp .env.test .env
- env
- export
script:
        #- docker pull aptrust/pharos:latest
- docker build --rm=false -t aptrust/pharos:latest  .
- docker network create -d bridge pharos-test-net
- docker run -d --network pharos-test-net -h pharos-test-db --name pharos-test-db
  -p 5432:5432 postgres:9.6.6-alpine
- docker run -e TRAVIS_JOB_ID="$TRAVIS_JOB_ID" -e TRAVIS_BRANCH="$TRAVIS_BRANCH" -e
  RAILS_ENV=test -e PHAROS_DB_NAME=travis_ci_test -e PHAROS_DB_HOST=pharos-test-db
  -e PHAROS_DB_USER=postgres --network pharos-test-net aptrust/pharos:latest /bin/bash
  -c "echo 'Init DB setup'; rake db:setup; rake db:migrate; rake pharos:setup; bin/rails
  spec"
deploy:
- provider: script
  script: make -w publish-ci
  on:
    branch: docker
  skip_cleanup: true
