language: ruby
sudo: required
services:
- docker
install: true
addons:
  apt:
    packages:
    - docker-ce
    - git
before_script:
- sudo service postgresql stop
- env
- export
env:
  global:
  - secure: QQnJi0gzmOj42XLp5P5juZdY41BGG3+uyV4NyFUHsUfkzeSKz63tkAXVWXF3DL6eFdXQhWgpXPDrdYlYwYa7T464hP3f+dxFOEhKLENWJgNdtQQnOWjoscnKnTBvjjarK/QMFcuG1a6IopbokWSuNkalFlbQYK2ZW72SEu7gj7bp3JcEVc+hXbWmAAyRRRdexGhZIigMR6MHDdKZ8AbYRaTNgZlDwOid8cL25PBQjpBPLigpqGXpzYynkwYWcyJCZUcEusuy4WzMAFQnGdHwpSr8tneVb+PZ3Rzvc5CfAeIO/KF/60bZe2mQeA2xPfURwcmRQ2AtVTWe2Yc20JgTpI98guJ2rBZ3U/j0JIqYwj0HM2cpiRbtU/jhIaMaynjJqR94iOGqPnjwcVSKBII3FKrEk2YEyIm5++Hbyfak2qozX25poYXMiXP1XKZnYGmMJvgxHoo6lhGoATSCA3PaMvMWegH4N7mBA84S6CFUyz/oq58GxdqY6rmMqtjuB+ELJGTpIEEKl7NFRo5eLQP3tlZB4C+urmgMFu0YpdAotUx/zVQrqknLiAh7PpsC6pjQFmzvhS+8IlJcHvyF78eCJS5sSWfIi7A78kVk8JZy4Iqh1efSZ6BIh1mjRingAii3TpUDvznF4ANR6BG8pxl2leawUgK9uFasaRnMjrS7UPo=
  - secure: SmLhixxIMzu5pJW2bwz33txH0W/0e0nuEugkGYDpfAAWQhEYgta7OhtNi/7m+UxlTbrYMirDLdcVV342CuV2c92k+0j97axX+gWmFIYGLg98fy6fRDXR+PlIjTrmRimzCY/WSRKDn02qBcsf/L1pTZRbI4mGf6gqorlIWioOow87V6OJt4GFzAMx35ADFAKQkr5RJBBkTzTf5fqUY3ugV1QC1BWp5Y8lTtTsIPbrYv4TBRpwoznRGCdvnkp75dnnsmsIbrxKxWS8ehBLOddUqPB7zrcQXgirb2r9IHtOzeUASjl1pX6rWNQFFCSfbD7gqavjjUXh9ZzfcR5VDk7tWguusWI7b5N9HKM5DUgkQ8Wg7pSrdwwl1j53mYcm0xeQdwwU0cTRTKv6Gam7L3Js4NN0MgSlrOk6J9TN4385g9mumzqzAV950/Kv13AsC9amqfadQrZpHSB/Rb8PY2VHCfREec7uzmgasUmPW0pJJzDsZjb37F1dLHjcNIYD57UJcVq5o/pPeh1QxCYPEXcKAGxsN9KjHr3FUOo7hjHPx+tZv40AW+80GlK7wLO+kI1Jn/EGdGHCngd2FoLG2gmNDOZafNNyKv9cU/7Kbw4PCx8vpRJYx+c0tMn8LdNM0yai1apatZZrujjqKBgG+9NmVYpPqVr50L3S0/xdFX/aT2U=
script:
- make test-ci
before_deploy:
- git config --local user.name "Deploy Fella"
- git config --local user.email "ops@aptrust.org"
- export TRAVIS_TAG=''
- export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
- git tag $TRAVIS_TAG
deploy:
- provider: script
  script: make -w publish-ci
  on:
    branch:
    - develop
    - master
  skip_cleanup: true
notifications:
  slack:
    secure: th9jcQKKUPZvtnaSwZJf0UdDYvY4bBof8ZrSX85aEbrW2TVUPWIi4+C73s8HXOgIrvTagiOmsUnapTxXgR93U+QixK9tpS/pqvT98LKdaTh3zc437pFKah9ZGKntOxdcQe6IWZUKKSG9lYBIImMbxskHNV4nHp++AniEqm9l/wzU0bjFlXmjlPjKilfX2UyTHGeNF1ID+2rVAdX9HlGPwlUzd67Kh40BKViL8bqUre2q0CXBheAOQ3LNNWDN6tKP3+eJr4DaSvq9M/4SZAUrQ8HWxRaNC5hMzT1zkxdoq4Tqc3D7/0cw9X2ZNmOxjq+erXrI0z91YhzKL6CYJlddsiw7Yhqwgx7uzA1G1Ee4FDuE5WFRmrarviUbk+FXO7vb6VoreHgLV4ER+yC1vaSEUNrOSR/XOSLWHha1/oKds4Mz+A3pVzsQ0Wl14SdF0W7IwTf5O4fX7NrBasIWZcipKWTOU2crgd8+Is7foer1EdIi13Cxq6oYDIeEfCrMCp8g+swmLrj85nGjoeODTALSVe5BllHDW2q9R9mdxyclNXCMHdE9U10pxUt3beXVr7F/3bG80u+U7fLe3StQTDgFynm6KOW3t0F3RntqUpjJUQADgAErsu4sQ2DAemYhk9IcCGQpw0RRWlHYL9gK7wORkxKCkQo/tbl6xSgHTIefgQE=
