ARG PRELEASE=latest
# Generate the assets
FROM pharos:$PRELEASE AS build
WORKDIR /pharos/public
# Build the final image used to serve them
FROM aptrust/nginx-proxy
COPY --from=build /pharos/public/* /usr/share/nginx/html/
