# This compose file needs
# - nginx container for forwarding
# - passenger? maybe just puma for the rails container
# - postgresql db if non-development
# - use sqlite for development.
#

app:
  build: .
  volumes:
    - .:/pharos
  links:
    - db
  environment:
    - DOCKERIZED=true
  env_file:
    - ".env"
  ports:
   - "3000:3000"

web:
  image: nginx:alpine
  container_name: nginx
  volumes:
    - /var/log/nginx:/var/log/nginx
  volumes_from:
    - pharos
  links:
    - app
  ports:
    - '80:443'
		- '443:443'

db:
  image: postgres:9.6.6-alpine
  container_name: postgres
  volumes:
    - ~/.docker-volumes/rails-app/postgresql/data:/var/lib/postgresql/data
  ports:
    - '5432:5432'

