# This compose file needs
# - nginx container for forwarding
# - passenger? maybe just puma for the rails container
# - postgresql db if non-development
# - use sqlite for development.
#
version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile-alpine
    image: pharos-test-2
    command: bundle exec puma -p9292 -e demo
    volumes:
      - .:/pharos
    links:
      - db
    environment:
      - DOCKERIZED=true
      - RAILS_ENV=demo
      - PHAROS_DB_HOST=localhost
      - PHAROS_DB_USER=
    ports:
     - "9292:9292"
    depends_on:
      - db

  web:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ./docker/nginx:/var/log/nginx
    links:
      - app
    ports:
      - '80:443'
      - '443:443'

  db:
    image: postgres:9.6.6-alpine
    container_name: postgres
    volumes:
      - ~/.docker-volumes/rails-app/postgresql/data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

