openapi: 3.0.1
info:
  description: >-
    This is the documentation for the APTrust Pharos Member API, which can be
    found in another location at
    [https://wiki.aptrust.org/Member_API](https://wiki.aptrust.org/Member_API).
    The Member API basepath is
    [https://repo.aptrust.org/member-api/v2](https://repo.aptrust.org/member-api/v2).
  version: 1.0.0
  title: APTrust Member API
  contact:
    email: help@aptrust.org
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0'
tags:
  - name: intellectual_object
    description: What your bags are translated into
  - name: generic_file
    description: Individual files in Intellectual Objects
  - name: premis_event
    description: Singular events that happen to Intellectual Objects and/or Generic Files
  - name: work_item
    description: >-
      An internal object that keeps track of the status of ingests, restoration,
      and deletion requests
  - name: dpn_bag
    description: Packaged bag version of an intellectual object to be sent to DPN
paths:
  /objects:
    get:
      tags:
        - intellectual_object
      summary: Index of Intellectual Objects
      description: >-
        Retrieves a list of all intellectual objects; limited by institution for
        all users below the level of APTrust administrator
      operationId: getObjects
      responses:
        default:
          description: Default error sample response